Marks = []
F1 = int(input("Enter the first mark: "))
Marks.append(F1)
F2 = int(input("Enter the second marks: "))
Marks.append(F2)
F3 = int(input("Enter the third marks: "))      
Marks.append(F3)
F4 = int(input("Enter the fourth marks: "))
Marks.append(F4)
F5 = int(input("Enter the fifth marks: "))
Marks.append(F5)
F6 = int(input("Enter the sixth marks: "))  
Marks.append(F6)
F7 = int(input("Enter the seventh marks: "))
Marks.append(F7)
Marks.sort()
print("The Marks you entered are:" , (Marks))