s = set()
n = input("Enter Your Number:")
s.add(int(n))
n = input("Enter Your Number:")
s.add(int(n))
n = input("Enter Your Number:")
s.add(int(n))
n = input("Enter Your Number:")
s.add(int(n))
n = input("Enter Your Number:")
s.add(int(n))
n = input("Enter Your Number:")
s.add(int(n))
n = input("Enter Your Number:")
s.add(int(n))
n = input("Enter Your Number:")
s.add(int(n))
print(s)